# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    container_name: server
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/bookdb?schema=public
    build:
      context: '.'
      target: base
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - test_vm
  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge
